// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGameSessionByIdData, GetGameSessionByIdErrors, GetGameSessionByIdResponses, ListGameSessionsData, ListGameSessionsErrors, ListGameSessionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all game sessions
 */
export const listGameSessions = <ThrowOnError extends boolean = false>(options?: Options<ListGameSessionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListGameSessionsResponses, ListGameSessionsErrors, ThrowOnError>({
        url: '/game-sessions',
        ...options
    });
};

/**
 * Get a single game session by UUID
 */
export const getGameSessionById = <ThrowOnError extends boolean = false>(options: Options<GetGameSessionByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetGameSessionByIdResponses, GetGameSessionByIdErrors, ThrowOnError>({
        url: '/game-sessions/{uuid}',
        ...options
    });
};
