// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.example.com' | (string & {});
};

export type SchemasErrorResponse = {
    error: string;
    message: string;
    /**
     * Optional structured error details
     */
    details?: {
        [key: string]: unknown;
    } | null;
};

export type SchemasGame = {
    uuid: string;
    name: string;
};

export type SchemasGameSession = {
    uuid: string;
    name: string;
    game: SchemasGame;
    status: SchemasGameSessionStatus;
    players: Array<SchemasGameSessionPlayer>;
    currentTurnIndex: number;
    createdAt: string;
    updatedAt?: string | null;
};

export type SchemasGameSessionPlayer = SchemasPlayer & {
    moves: Array<SchemasPlayerMove>;
    status: SchemasGameSessionPlayerStatus;
    previousTotalTimeMs: number;
    turnOrderIndex: number;
};

export type SchemasGameSessionPlayerStatus = 'playing' | 'waiting' | 'passed';

export type SchemasGameSessionStatus = 'in_progress' | 'paused' | 'completed';

export type SchemasPlayer = {
    uuid: string;
    name: string;
};

export type SchemasPlayerMove = {
    startTimestamp: string;
    endTimestamp?: string | null;
    moveIndex: number;
    turnIndex: number;
};

export type GameSessions1GameSessions = unknown;

export type GameSessions1GameSessions1Uuid = unknown;

export type Games1Games = unknown;

export type Games1Games1Uuid = unknown;

export type IndexRoot = unknown;

export type Players1Players = unknown;

export type Players1Players1Uuid = unknown;
