// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CommonTimestamp = string;

export type CommonUuid = string;

export type ErrorResponse = {
    error: string;
    message: string;
    statusCode: number;
};

export type GameSessionPlayer = PlayerResource & {
    moves?: Array<GameSessionPlayerMove>;
    status: GameSessionPlayerStatus;
    previousTotalTimeMs?: number;
    turnOrderIndex: number;
};

export type GameSessionPlayerMove = {
    startTimestamp: CommonTimestamp;
    endTimestamp?: CommonTimestamp;
    moveIndex: number;
    turnIndex: number;
};

export type GameSessionPlayerStatus = 'playing' | 'waiting' | 'passed';

export type GameSessionResource = {
    uuid: CommonUuid;
    name: string;
    game: GameResource;
    status: GameSessionStatus;
    players: Array<GameSessionPlayer>;
    currentTurnIndex: number;
    createdAt: CommonTimestamp;
    updatedAt?: CommonTimestamp;
};

export type GameSessionStatus = 'in_progress' | 'paused' | 'completed';

export type GameResource = {
    uuid: CommonUuid;
    name: string;
};

export type PlayerResource = {
    uuid: CommonUuid;
    name: string;
};

export type GameSessionsDetailRoot = unknown;

export type GameSessionsListRoot = unknown;

export type ListGameSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/game-sessions';
};

export type ListGameSessionsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListGameSessionsError = ListGameSessionsErrors[keyof ListGameSessionsErrors];

export type ListGameSessionsResponses = {
    /**
     * Paginated list of game sessions
     */
    200: {
        data: Array<GameSessionResource>;
        meta: {
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
    };
};

export type ListGameSessionsResponse = ListGameSessionsResponses[keyof ListGameSessionsResponses];

export type GetGameSessionByIdData = {
    body?: never;
    path: {
        uuid: CommonUuid;
    };
    query?: never;
    url: '/game-sessions/{uuid}';
};

export type GetGameSessionByIdErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetGameSessionByIdError = GetGameSessionByIdErrors[keyof GetGameSessionByIdErrors];

export type GetGameSessionByIdResponses = {
    /**
     * Single game session
     */
    200: {
        data: GameSessionResource;
    };
};

export type GetGameSessionByIdResponse = GetGameSessionByIdResponses[keyof GetGameSessionByIdResponses];
